version: '3.7'
services:
  Service1:
    build: ./Service1/application
    image: marti/Service1:latest
    container_name: Service1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp

  Service2:
    build: ./Service2/application
    image: marti/Service2:latest
    container_name: Service2
    ports:
    - target: 5001
      published: 5001
      protocol: tcp

  Service3:
    build: ./Service3/application
    image: marti/Service3:latest
    container_name: Service3
    ports:
    - target: 5002
      published: 5002
      protocol: tcp

  Service4:
    build: ./Service4/application
    image: marti/Service4:latest
    container_name: Service4
    ports:
    - target: 5003
      published: 5003
      protocol: tcp